apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kub-test.fullname" . }}
  labels:
  {{- include "kub-test.labels" . | nindent 4 }}
data:
  application.yaml: |-
    supreme:
      const: configMapWorks!