
management:
  server:
    port: 8081
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
        - health
        - info
        - prometheus
        - restart
        - refresh
        - shutdown
server:
  port: 8080

supreme:
  const: configMapTest