apiVersion: apps/v1
kind: Service
metadata:
  name: supreme-test-nodePort
  namespace: default
spec:
  type: NodePort
  selector:
    app: some-selector
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP